FORMAT: 1A
HOST: https://localhost/

# UAS_RekayasaAplikasiTerdistribusi


## List Drink Recipe [/Drinks]

### List All Drink Recipe [GET/Drinks/Get.php]

For those who want to see all the Recipe that the Database have :

+ Response 200 (application/json)

        {
          "drink": [
            {
              "Name": "BlackBerry Mojito ",
              "Type": "Refresh, Non-Alcohol",
              "Desc": "A guilt-free strawberry milkshake that both kids and adults will enjoy.",
              "Ing": "- 1/2 c. blackberries\n- handful fresh mint leaves\n- Juice of 2 limes\n- 1 tsp. sugar\n- 1/2 c. light rum\n- Crushed ice\n- club soda",
              "Step": "- In a small bowl, muddle blackberries. Set aside.\n- Place mint leaves in bottom of glasses. Divide and spoon blackberry mixture on top.\n- Add rum, sugar, and lime juice and stir to combine. Top with crushed ice.\n- Add club soda and garnish with mint leaves and more blackberries."
            },
            {
              "Name": "Blackberry Mojito",
              "Type": "Alcoholic Cocktail",
              "Desc": "Crushed, ripe blackberries give this mojito a tart-sweet kick.",
              "Ing": "1/2 c. blackberries\nhandful fresh mint leaves\nJuice of 2 limes\n1 tsp. sugar\n1/2 c. light rum\nCrushed ice\nclub soda",
              "Step": "- In a small bowl, muddle blackberries. Set aside.\n- Place mint leaves in bottom of glasses. Divide and spoon blackberry mixture on top.\n- Add rum, sugar, and lime juice and stir to combine. Top with crushed ice.\n- Add club soda and garnish with mint leaves and more blackberries."
            },
            {
              "Name": "Skinny Strawberry Milkshake",
              "Type": "Milkshake, Ice",
              "Desc": "A guilt-free strawberry milkshake that both kids and adults will enjoy.",
              "Ing": "- 1 cup 2% milk, divided\n- 2 cups hulled and halved strawberries\n- 1 teaspoon fresh lime juice, or more to taste\n- 1 teaspoon vanilla extract",
              "Step": "- Pour 1/2 cup milk into an ice cube tray and freeze until firm.\n- Combine milk ice cubes, remaining 1/2 cup milk, strawberries, lime juice, and vanilla in a blender; blend until smooth. Serve immediately."
            }
          ]
        }

### Create a New Drink Recipe [POST]

For those who wants to share their own Drink Recipe :

+ Request (application/json)

        {
            "drink": [
                {
                  "Name": "Drink Name",
                  "Type": "Drink Type",
                  "Desc": "Description about the Drink",
                  "Ing": "Ingredients for making the Drink",
                  "Step": "Step by step how to make the Drink"
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /Drinks/Post.php

    + Body

            {
                "drink": [
                    {
                      "Name": "",
                      "Type": "",
                      "Desc": "",
                      "Ing": "",
                      "Step": ""
                    }
                ]
            }

### Edit Drink Recipe [PUT]

For those who already put their recipe in the database but put the wrong data, they can edit it:

+ Request (application/json)

        {
            "drink": [
                {
                    "ID": "Drink ID",
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /Drinks/put

    + Body

            {
                "drink": [
                    {
                      "Name": "",
                      "Type": "",
                      "Desc": "",
                      "Ing": "",
                      "Step": ""
                    }
                ]
            }
            
### Delete Drink Recipe [DELETE/uas/delete]

For those who want to Delete Their Recipe from Database

+ Request (application/json)

        {
            "drink": [
                {
                    "ID": "Drink ID",
                }
            ]
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /Drinks/delete

    + Body

            {
                " There's a problem when we want to delete the data "
            }